<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>src</string>
	</array>
	<key>name</key>
	<string>Custom</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.c++</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#project_types</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>project_types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bFoo\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bBar\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bTaskingScheduler\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bTaskingSchedulerStatistics\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bAggregator\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bAggregatorGenericCallHeader\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\btask_worker_args\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\brange_t\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bThreadQueue\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bTaskStatistics\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\btest1_id\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bResultPair\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bScheduler\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bArgumentPair\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bPair\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCommunicator\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bAtomicAddDouble\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bTask\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bworkStealRequest_args\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bThread\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bReceivedAM\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bTaskManager\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCommunicatorStatistics\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bAggregatorStatistics\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bDelegateCallbackArgs\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bStateTimer\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bDelegateStatistics\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bLRQueue\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bLREntry\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bworkStealReply_args\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bFunctor\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\btest1\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\barray_element\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bBrandonM32\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bthreeword_array_element\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bBrandonM\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bBrandonM64\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bremote_task_spawn_args\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bAggregatorBuffer\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bGlobalAddress\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bStealQueue\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bNullAcquirer\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bIncoherentAcquirer\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bread_request_args\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bIncoherent\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bAllocatorChunk\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bread_reply_args\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bNullReleaser\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bgeneric_delegate_request_args\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCacheAllocator\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCacheRO\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bIncoherentReleaser\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bgeneric_delegate_reply_args\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCacheStatistics\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCacheRW\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bIAStatistics\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bDescriptor\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bIRStatistics\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bRequestArgs\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bReplyArgs\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bGlobalAllocator\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bmemory_desc\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bAllocator\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCacheWO\b</string>
					<key>name</key>
					<string>support.type.project.clang</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.clang</string>
	<key>uuid</key>
	<string>A97121E9-D3C1-4B1F-B55D-B97193A8A996</string>
</dict>
</plist>
