<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>src</string>
	</array>
	<key>injectionSelector</key>
	<string>source.c++</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>Linguist&lt;C++&gt;</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.c++</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#project_types</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>project_types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\btuple_graph\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bcsr_graph\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bedges_ptr_t\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bpacked_edge\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bTaskingScheduler\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bTaskingSchedulerStatistics\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCompletionMessage\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bReduction\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCoreData\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bPoolExternalMessage\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bblock_offset_t\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bMessageBase\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bScheduler\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCommunicator\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bAggregatorGenericCallHeader\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bPool\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bInplaceReduction\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bTask\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bThread\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bTaskManager\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bStatisticBase\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bDeserializer\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bDelegateStatistics\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCountingSemaphore\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bPrefetchEntry\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bSharedMessagePool\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bExternalMessage\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bFunctor\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bWarning\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bGlobalCompletionEvent\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bMutexConditionVariable\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bAggregator\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bReusePool\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\barg\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bWorker\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bAggregatorAMHandler\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bGrappa_Timestamp\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bSummarizingStatistic\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bMessagePool\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bReuseList\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bReceivedAM\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bgeneric_delegate_request_args\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bHeapF\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bDelegateCallbackArgs\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bLRQueue\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bLREntry\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bthread_func\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bMessage\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bLocaleSharedMemory\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bMessagePoolBase\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\brange_t\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bNode\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCore\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bRunningStandardDeviation\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bPoolMessage\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bcoro_func\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bDoComplete\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bPoolPayloadMessage\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bread_reply_args\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bthread_fn\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bPoolExternalPayloadMessage\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bAggregatorBuffer\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bGlobalAddress\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bMessageList\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bfn_t\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bSendBufferInfo\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bAggregatorStatistics\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bthreadid_t\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bReductions\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bHandlerPointer\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bMessagePoolStatic\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bExternalPayloadMessage\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bfunction_traits\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bremote_task_spawn_args\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bSimpleStatistic\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bMutex\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bConditionVariable\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\btask_worker_args\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bTaskStatistics\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCompletionEvent\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bRDMABuffer\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bExampleMutexOrConditionVariableOrFullBit\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bRDMAAggregator\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bPoolAllocatorInternal\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCommunicatorStatistics\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bFullEmpty\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bTotalStatistic\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bread_request_args\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bStateTimer\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bPoolAllocator\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bPayloadMessage\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bgeneric_delegate_reply_args\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bLocale\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bReceiveBufferInfo\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bmemory_desc\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bresult_type\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bNullAcquirer\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bWO\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bIncoherentAcquirer\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bRequestArgs\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bRW\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bRO\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bAllocatorChunk\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bFreeListMap\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCacheWO\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bMaster\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCacheRO\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bAllocatorAddress\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bIncoherentReleaser\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bGlobalVector\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bIncoherent\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bIAStatistics\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCacheStatistics\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bIRStatistics\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bShared\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bNullReleaser\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bChunkMap\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCacheRW\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCacheAllocator\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bAllocator\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bFreeList\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bPushCombiner\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bGlobalAllocator\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bbfs_tree_entry\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bBFSTreeEntry\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bBFSParent\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bFlusher\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bFlatCombiner\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCounter\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\btest1_id\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\btest1\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bProxy\b</string>
					<key>name</key>
					<string>support.type.project.linguist</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.linguist</string>
	<key>uuid</key>
	<string>F8B47E84-6474-462C-B209-E42E05E314C1</string>
</dict>
</plist>
